---
- hosts: all
  become: true
  tasks:

  - name: install latest pip3
    yum:
      name:
        - pip3
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install latest pip3
    yum:
      name:
        - pip3
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
